### ISSUE TITLE
Missing dependency: requests

### ISSUE THREAD

**Issue by hukka** [sensu-plugins/sensu-plugin-python#28]
Using `pip install sensu-plugin` will not install requests, breaking SensuPlugin import:

```
$ python sensu.py 
Traceback (most recent call last):
  File "sensu.py", line 2, in <module>
    from sensu_plugin import SensuPlugin
  File "/home/hukka/.pyenv/versions/browsertests/lib/python3.6/site-packages/sensu_plugin/__init__.py", line 7, in <module>
    from sensu_plugin.handler import SensuHandler
  File "/home/hukka/.pyenv/versions/browsertests/lib/python3.6/site-packages/sensu_plugin/handler.py", line 18, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by barryorourke** [comment]
thats 0.4.1 uploaded to PyPI, thanks again for reporting.
