### ISSUE TITLE
setup.py doesn't specify the utils package

### ISSUE THREAD

**Issue by hukka** [sensu-plugins/sensu-plugin-python#29]
https://github.com/sensu-plugins/sensu-plugin-python/blob/master/setup.py#L8 doesn't list the utils subpackage, breaking importing SensuPlugin after `pip install sensu-plugin`:

```
$ python sensu.py 
Traceback (most recent call last):
  File "sensu.py", line 2, in <module>
    from sensu_plugin import SensuPlugin
  File "/home/hukka/.pyenv/versions/browsertests/lib/python3.6/site-packages/sensu_plugin/__init__.py", line 7, in <module>
    from sensu_plugin.handler import SensuHandler
  File "/home/hukka/.pyenv/versions/browsertests/lib/python3.6/site-packages/sensu_plugin/handler.py", line 23, in <module>
    from sensu_plugin.utils import get_settings
ModuleNotFoundError: No module named 'sensu_plugin.utils'
```

```
$ ls /home/hukka/.pyenv/versions/browsertests/lib/python3.6/site-packages/sensu_plugin
check.py   exithook.py  __init__.py  plugin.py     __pycache__
compat.py  handler.py   metric.py    pushevent.py  test
```

**Comment by barryorourke** [comment]
Thanks for highlighting this issue and the other one that you submitted, I'll hopefully have time later today to get these sorted out.

**Comment by barryorourke** [comment]
That's 0.4.1 uploaded to PyPI, thanks again for reporting this :)
